version: 2

sources:
  - name: demo_raw
    database: demo

    tables:
      - name: order_lines
      - name: products
      - name: customers
      - name: site_events
      - name: marketing_spend
      - name: returns
      - name: order_info
      - name: click_info
      
      